export const EnvKeys = {
  DATABASE_URL: 'DATABASE_URL',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_USERNAME: 'REDIS_USERNAME',
  REDIS_PASSWORD: 'REDIS_PASSWORD',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRATION: 'JWT_EXPIRATION',
  PORT: 'PORT',
} as const;
